### ISSUE TITLE
 Legacy model format is not supported on mobile.

### ISSUE THREAD

**Issue by tdas714** [pytorch/android-demo-app#37] opened 2019-11-26 04:46 UTC
Hi , I'm trying to load a custom model on mobile device , 
error : Caused by: com.facebook.jni.CppException: Legacy model format is not supported on mobile. (deserialize at /var/lib/jenkins/workspace/torch/csrc/jit/import.cpp:201)
    (no backtrace available)

Can anybody tell me, what does that mean. what is legacy model format???

**Comment by IvanKobzarev** [comment] 2019-11-28 00:01
Hello @tdas714,

This error usually happens when the model was traced/scripted with version of pytorch python package  different with the version of pytorch_android build.

To check the version of your current python packages:
```
$ python -c 'import torch; print(torch.version.__version__)'
1.4.0.dev20191119
```

If it is possible for you, I recommend to install pytorch python nightlly, for linux-conda-python3.7-cpu that is:
```
conda install pytorch torchvision cpuonly -c pytorch-nightly
```
to trace/script your model with it.


And use pytorch android nightlies:
(to force refresh dependencies gradle has argument `--refresh-dependencies`)
```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
    ...
    implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'
    ...
}
```
In that case version of `pt` will be aligned with android part.

Or if model was scripted with pytorch 1.3.0 or 1.3.1 you should use the same version of pytorch_android dependencies.

**Comment by tdas714** [comment] 2019-11-28 11:19
Thanks, But I'm having another error in trying to convert through torch.jit.trace(). it says
torch.jit.frontend.UnsupportedNodeError: GeneratorExp aren't supported:

torch.jit.frontend.UnsupportedNodeError: GeneratorExp aren't supported:
  File "/home/tapas/anaconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 114
        # Module.named_parameters().
        all_weights = self._flat_weights
        unique_data_ptrs = set(**p**.data_ptr() for p in all_weights)
                               ~ <--- HERE
        if len(unique_data_ptrs) != len(all_weights):
            return

**Comment by dreiss** [comment] 2019-12-05 00:48
Looks like you're being hit by https://github.com/pytorch/pytorch/issues/28418

**Comment by dreiss** [comment] 2019-12-05 00:48
I'm going to close this for now because the issue is with TorchScript and isn't related to Android.

**Closed by dreiss** 2019-12-05 00:48 UTC
